export const SET_LOADING_CATEGORIES_STATUS = 'APP/SET_LOADING_CATEGORIES_STATUS'
export const SET_LOADING_CATS_STATUS = 'APP/SET_LOADING_CATS_STATUS'
export const SET_CATEGORES = 'DATA/SET_CATEGORES'
export const SET_CATS = 'DATA/SET_CATS'